/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DebtsReceivablesRouteImport } from './routes/debts-receivables'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransactionsRouteRouteImport } from './routes/api/transactions/route'
import { Route as ApiRecurringTransactionsRouteRouteImport } from './routes/api/recurring-transactions/route'
import { Route as ApiReceivablesRouteRouteImport } from './routes/api/receivables/route'
import { Route as ApiInvestmentsRouteRouteImport } from './routes/api/investments/route'
import { Route as ApiFinancialGoalsRouteRouteImport } from './routes/api/financial-goals/route'
import { Route as ApiDebtsRouteRouteImport } from './routes/api/debts/route'
import { Route as ApiDashboardRouteRouteImport } from './routes/api/dashboard/route'
import { Route as ApiBudgetsRouteRouteImport } from './routes/api/budgets/route'
import { Route as ApiBillRemindersRouteRouteImport } from './routes/api/bill-reminders/route'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiTransactionsSummaryRouteRouteImport } from './routes/api/transactions/summary/route'
import { Route as ApiTransactionsIdRouteRouteImport } from './routes/api/transactions/$id/route'
import { Route as ApiRecurringTransactionsIdRouteRouteImport } from './routes/api/recurring-transactions/$id/route'
import { Route as ApiInvestmentsSummaryRouteRouteImport } from './routes/api/investments/summary/route'
import { Route as ApiInvestmentsHistoryRouteRouteImport } from './routes/api/investments/history/route'
import { Route as ApiInvestmentsAccountsRouteRouteImport } from './routes/api/investments/accounts/route'
import { Route as ApiInvestmentsIdRouteRouteImport } from './routes/api/investments/$id/route'
import { Route as ApiFinancialGoalsIdRouteRouteImport } from './routes/api/financial-goals/$id/route'
import { Route as ApiDebtsReceivablesSummaryRouteRouteImport } from './routes/api/debts-receivables/summary/route'
import { Route as ApiBudgetsIdRouteRouteImport } from './routes/api/budgets/$id/route'
import { Route as ApiBillRemindersIdRouteRouteImport } from './routes/api/bill-reminders/$id/route'
import { Route as ApiAuthRegisterRouteRouteImport } from './routes/api/auth/register/route'
import { Route as ApiAuthMeRouteRouteImport } from './routes/api/auth/me/route'
import { Route as ApiAuthLogoutRouteRouteImport } from './routes/api/auth/logout/route'
import { Route as ApiAuthLoginRouteRouteImport } from './routes/api/auth/login/route'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiReceivablesIdCollectRouteRouteImport } from './routes/api/receivables/$id/collect/route'
import { Route as ApiFinancialGoalsIdContributeRouteRouteImport } from './routes/api/financial-goals/$id/contribute/route'
import { Route as ApiDebtsIdSettleRouteRouteImport } from './routes/api/debts/$id/settle/route'
import { Route as ApiBillRemindersIdPayRouteRouteImport } from './routes/api/bill-reminders/$id/pay/route'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsReceivablesRoute = DebtsReceivablesRouteImport.update({
  id: '/debts-receivables',
  path: '/debts-receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRouteRoute = ApiTransactionsRouteRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecurringTransactionsRouteRoute =
  ApiRecurringTransactionsRouteRouteImport.update({
    id: '/api/recurring-transactions',
    path: '/api/recurring-transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReceivablesRouteRoute = ApiReceivablesRouteRouteImport.update({
  id: '/api/receivables',
  path: '/api/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestmentsRouteRoute = ApiInvestmentsRouteRouteImport.update({
  id: '/api/investments',
  path: '/api/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinancialGoalsRouteRoute = ApiFinancialGoalsRouteRouteImport.update({
  id: '/api/financial-goals',
  path: '/api/financial-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebtsRouteRoute = ApiDebtsRouteRouteImport.update({
  id: '/api/debts',
  path: '/api/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRouteRoute = ApiDashboardRouteRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBudgetsRouteRoute = ApiBudgetsRouteRouteImport.update({
  id: '/api/budgets',
  path: '/api/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillRemindersRouteRoute = ApiBillRemindersRouteRouteImport.update({
  id: '/api/bill-reminders',
  path: '/api/bill-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsSummaryRouteRoute =
  ApiTransactionsSummaryRouteRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => ApiTransactionsRouteRoute,
  } as any)
const ApiTransactionsIdRouteRoute = ApiTransactionsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTransactionsRouteRoute,
} as any)
const ApiRecurringTransactionsIdRouteRoute =
  ApiRecurringTransactionsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiRecurringTransactionsRouteRoute,
  } as any)
const ApiInvestmentsSummaryRouteRoute =
  ApiInvestmentsSummaryRouteRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => ApiInvestmentsRouteRoute,
  } as any)
const ApiInvestmentsHistoryRouteRoute =
  ApiInvestmentsHistoryRouteRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiInvestmentsRouteRoute,
  } as any)
const ApiInvestmentsAccountsRouteRoute =
  ApiInvestmentsAccountsRouteRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => ApiInvestmentsRouteRoute,
  } as any)
const ApiInvestmentsIdRouteRoute = ApiInvestmentsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvestmentsRouteRoute,
} as any)
const ApiFinancialGoalsIdRouteRoute =
  ApiFinancialGoalsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiFinancialGoalsRouteRoute,
  } as any)
const ApiDebtsReceivablesSummaryRouteRoute =
  ApiDebtsReceivablesSummaryRouteRouteImport.update({
    id: '/api/debts-receivables/summary',
    path: '/api/debts-receivables/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBudgetsIdRouteRoute = ApiBudgetsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBudgetsRouteRoute,
} as any)
const ApiBillRemindersIdRouteRoute = ApiBillRemindersIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBillRemindersRouteRoute,
} as any)
const ApiAuthRegisterRouteRoute = ApiAuthRegisterRouteRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRouteRoute = ApiAuthMeRouteRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRouteRoute = ApiAuthLogoutRouteRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRouteRoute = ApiAuthLoginRouteRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceivablesIdCollectRouteRoute =
  ApiReceivablesIdCollectRouteRouteImport.update({
    id: '/$id/collect',
    path: '/$id/collect',
    getParentRoute: () => ApiReceivablesRouteRoute,
  } as any)
const ApiFinancialGoalsIdContributeRouteRoute =
  ApiFinancialGoalsIdContributeRouteRouteImport.update({
    id: '/contribute',
    path: '/contribute',
    getParentRoute: () => ApiFinancialGoalsIdRouteRoute,
  } as any)
const ApiDebtsIdSettleRouteRoute = ApiDebtsIdSettleRouteRouteImport.update({
  id: '/$id/settle',
  path: '/$id/settle',
  getParentRoute: () => ApiDebtsRouteRoute,
} as any)
const ApiBillRemindersIdPayRouteRoute =
  ApiBillRemindersIdPayRouteRouteImport.update({
    id: '/pay',
    path: '/pay',
    getParentRoute: () => ApiBillRemindersIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debts-receivables': typeof DebtsReceivablesRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/bill-reminders': typeof ApiBillRemindersRouteRouteWithChildren
  '/api/budgets': typeof ApiBudgetsRouteRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRouteRoute
  '/api/debts': typeof ApiDebtsRouteRouteWithChildren
  '/api/financial-goals': typeof ApiFinancialGoalsRouteRouteWithChildren
  '/api/investments': typeof ApiInvestmentsRouteRouteWithChildren
  '/api/receivables': typeof ApiReceivablesRouteRouteWithChildren
  '/api/recurring-transactions': typeof ApiRecurringTransactionsRouteRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/auth/logout': typeof ApiAuthLogoutRouteRoute
  '/api/auth/me': typeof ApiAuthMeRouteRoute
  '/api/auth/register': typeof ApiAuthRegisterRouteRoute
  '/api/bill-reminders/$id': typeof ApiBillRemindersIdRouteRouteWithChildren
  '/api/budgets/$id': typeof ApiBudgetsIdRouteRoute
  '/api/debts-receivables/summary': typeof ApiDebtsReceivablesSummaryRouteRoute
  '/api/financial-goals/$id': typeof ApiFinancialGoalsIdRouteRouteWithChildren
  '/api/investments/$id': typeof ApiInvestmentsIdRouteRoute
  '/api/investments/accounts': typeof ApiInvestmentsAccountsRouteRoute
  '/api/investments/history': typeof ApiInvestmentsHistoryRouteRoute
  '/api/investments/summary': typeof ApiInvestmentsSummaryRouteRoute
  '/api/recurring-transactions/$id': typeof ApiRecurringTransactionsIdRouteRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRouteRoute
  '/api/transactions/summary': typeof ApiTransactionsSummaryRouteRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/bill-reminders/$id/pay': typeof ApiBillRemindersIdPayRouteRoute
  '/api/debts/$id/settle': typeof ApiDebtsIdSettleRouteRoute
  '/api/financial-goals/$id/contribute': typeof ApiFinancialGoalsIdContributeRouteRoute
  '/api/receivables/$id/collect': typeof ApiReceivablesIdCollectRouteRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debts-receivables': typeof DebtsReceivablesRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/bill-reminders': typeof ApiBillRemindersRouteRouteWithChildren
  '/api/budgets': typeof ApiBudgetsRouteRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRouteRoute
  '/api/debts': typeof ApiDebtsRouteRouteWithChildren
  '/api/financial-goals': typeof ApiFinancialGoalsRouteRouteWithChildren
  '/api/investments': typeof ApiInvestmentsRouteRouteWithChildren
  '/api/receivables': typeof ApiReceivablesRouteRouteWithChildren
  '/api/recurring-transactions': typeof ApiRecurringTransactionsRouteRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/auth/logout': typeof ApiAuthLogoutRouteRoute
  '/api/auth/me': typeof ApiAuthMeRouteRoute
  '/api/auth/register': typeof ApiAuthRegisterRouteRoute
  '/api/bill-reminders/$id': typeof ApiBillRemindersIdRouteRouteWithChildren
  '/api/budgets/$id': typeof ApiBudgetsIdRouteRoute
  '/api/debts-receivables/summary': typeof ApiDebtsReceivablesSummaryRouteRoute
  '/api/financial-goals/$id': typeof ApiFinancialGoalsIdRouteRouteWithChildren
  '/api/investments/$id': typeof ApiInvestmentsIdRouteRoute
  '/api/investments/accounts': typeof ApiInvestmentsAccountsRouteRoute
  '/api/investments/history': typeof ApiInvestmentsHistoryRouteRoute
  '/api/investments/summary': typeof ApiInvestmentsSummaryRouteRoute
  '/api/recurring-transactions/$id': typeof ApiRecurringTransactionsIdRouteRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRouteRoute
  '/api/transactions/summary': typeof ApiTransactionsSummaryRouteRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/bill-reminders/$id/pay': typeof ApiBillRemindersIdPayRouteRoute
  '/api/debts/$id/settle': typeof ApiDebtsIdSettleRouteRoute
  '/api/financial-goals/$id/contribute': typeof ApiFinancialGoalsIdContributeRouteRoute
  '/api/receivables/$id/collect': typeof ApiReceivablesIdCollectRouteRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debts-receivables': typeof DebtsReceivablesRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/bill-reminders': typeof ApiBillRemindersRouteRouteWithChildren
  '/api/budgets': typeof ApiBudgetsRouteRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRouteRoute
  '/api/debts': typeof ApiDebtsRouteRouteWithChildren
  '/api/financial-goals': typeof ApiFinancialGoalsRouteRouteWithChildren
  '/api/investments': typeof ApiInvestmentsRouteRouteWithChildren
  '/api/receivables': typeof ApiReceivablesRouteRouteWithChildren
  '/api/recurring-transactions': typeof ApiRecurringTransactionsRouteRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/auth/logout': typeof ApiAuthLogoutRouteRoute
  '/api/auth/me': typeof ApiAuthMeRouteRoute
  '/api/auth/register': typeof ApiAuthRegisterRouteRoute
  '/api/bill-reminders/$id': typeof ApiBillRemindersIdRouteRouteWithChildren
  '/api/budgets/$id': typeof ApiBudgetsIdRouteRoute
  '/api/debts-receivables/summary': typeof ApiDebtsReceivablesSummaryRouteRoute
  '/api/financial-goals/$id': typeof ApiFinancialGoalsIdRouteRouteWithChildren
  '/api/investments/$id': typeof ApiInvestmentsIdRouteRoute
  '/api/investments/accounts': typeof ApiInvestmentsAccountsRouteRoute
  '/api/investments/history': typeof ApiInvestmentsHistoryRouteRoute
  '/api/investments/summary': typeof ApiInvestmentsSummaryRouteRoute
  '/api/recurring-transactions/$id': typeof ApiRecurringTransactionsIdRouteRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRouteRoute
  '/api/transactions/summary': typeof ApiTransactionsSummaryRouteRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/bill-reminders/$id/pay': typeof ApiBillRemindersIdPayRouteRoute
  '/api/debts/$id/settle': typeof ApiDebtsIdSettleRouteRoute
  '/api/financial-goals/$id/contribute': typeof ApiFinancialGoalsIdContributeRouteRoute
  '/api/receivables/$id/collect': typeof ApiReceivablesIdCollectRouteRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/debts-receivables'
    | '/expenses'
    | '/income'
    | '/investments'
    | '/login'
    | '/register'
    | '/api/bill-reminders'
    | '/api/budgets'
    | '/api/dashboard'
    | '/api/debts'
    | '/api/financial-goals'
    | '/api/investments'
    | '/api/receivables'
    | '/api/recurring-transactions'
    | '/api/transactions'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/bill-reminders/$id'
    | '/api/budgets/$id'
    | '/api/debts-receivables/summary'
    | '/api/financial-goals/$id'
    | '/api/investments/$id'
    | '/api/investments/accounts'
    | '/api/investments/history'
    | '/api/investments/summary'
    | '/api/recurring-transactions/$id'
    | '/api/transactions/$id'
    | '/api/transactions/summary'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/bill-reminders/$id/pay'
    | '/api/debts/$id/settle'
    | '/api/financial-goals/$id/contribute'
    | '/api/receivables/$id/collect'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/debts-receivables'
    | '/expenses'
    | '/income'
    | '/investments'
    | '/login'
    | '/register'
    | '/api/bill-reminders'
    | '/api/budgets'
    | '/api/dashboard'
    | '/api/debts'
    | '/api/financial-goals'
    | '/api/investments'
    | '/api/receivables'
    | '/api/recurring-transactions'
    | '/api/transactions'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/bill-reminders/$id'
    | '/api/budgets/$id'
    | '/api/debts-receivables/summary'
    | '/api/financial-goals/$id'
    | '/api/investments/$id'
    | '/api/investments/accounts'
    | '/api/investments/history'
    | '/api/investments/summary'
    | '/api/recurring-transactions/$id'
    | '/api/transactions/$id'
    | '/api/transactions/summary'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/bill-reminders/$id/pay'
    | '/api/debts/$id/settle'
    | '/api/financial-goals/$id/contribute'
    | '/api/receivables/$id/collect'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/debts-receivables'
    | '/expenses'
    | '/income'
    | '/investments'
    | '/login'
    | '/register'
    | '/api/bill-reminders'
    | '/api/budgets'
    | '/api/dashboard'
    | '/api/debts'
    | '/api/financial-goals'
    | '/api/investments'
    | '/api/receivables'
    | '/api/recurring-transactions'
    | '/api/transactions'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/bill-reminders/$id'
    | '/api/budgets/$id'
    | '/api/debts-receivables/summary'
    | '/api/financial-goals/$id'
    | '/api/investments/$id'
    | '/api/investments/accounts'
    | '/api/investments/history'
    | '/api/investments/summary'
    | '/api/recurring-transactions/$id'
    | '/api/transactions/$id'
    | '/api/transactions/summary'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/bill-reminders/$id/pay'
    | '/api/debts/$id/settle'
    | '/api/financial-goals/$id/contribute'
    | '/api/receivables/$id/collect'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DebtsReceivablesRoute: typeof DebtsReceivablesRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomeRoute: typeof IncomeRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiBillRemindersRouteRoute: typeof ApiBillRemindersRouteRouteWithChildren
  ApiBudgetsRouteRoute: typeof ApiBudgetsRouteRouteWithChildren
  ApiDashboardRouteRoute: typeof ApiDashboardRouteRoute
  ApiDebtsRouteRoute: typeof ApiDebtsRouteRouteWithChildren
  ApiFinancialGoalsRouteRoute: typeof ApiFinancialGoalsRouteRouteWithChildren
  ApiInvestmentsRouteRoute: typeof ApiInvestmentsRouteRouteWithChildren
  ApiReceivablesRouteRoute: typeof ApiReceivablesRouteRouteWithChildren
  ApiRecurringTransactionsRouteRoute: typeof ApiRecurringTransactionsRouteRouteWithChildren
  ApiTransactionsRouteRoute: typeof ApiTransactionsRouteRouteWithChildren
  ApiAuthLoginRouteRoute: typeof ApiAuthLoginRouteRoute
  ApiAuthLogoutRouteRoute: typeof ApiAuthLogoutRouteRoute
  ApiAuthMeRouteRoute: typeof ApiAuthMeRouteRoute
  ApiAuthRegisterRouteRoute: typeof ApiAuthRegisterRouteRoute
  ApiDebtsReceivablesSummaryRouteRoute: typeof ApiDebtsReceivablesSummaryRouteRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts-receivables': {
      id: '/debts-receivables'
      path: '/debts-receivables'
      fullPath: '/debts-receivables'
      preLoaderRoute: typeof DebtsReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring-transactions': {
      id: '/api/recurring-transactions'
      path: '/api/recurring-transactions'
      fullPath: '/api/recurring-transactions'
      preLoaderRoute: typeof ApiRecurringTransactionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receivables': {
      id: '/api/receivables'
      path: '/api/receivables'
      fullPath: '/api/receivables'
      preLoaderRoute: typeof ApiReceivablesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investments': {
      id: '/api/investments'
      path: '/api/investments'
      fullPath: '/api/investments'
      preLoaderRoute: typeof ApiInvestmentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/financial-goals': {
      id: '/api/financial-goals'
      path: '/api/financial-goals'
      fullPath: '/api/financial-goals'
      preLoaderRoute: typeof ApiFinancialGoalsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debts': {
      id: '/api/debts'
      path: '/api/debts'
      fullPath: '/api/debts'
      preLoaderRoute: typeof ApiDebtsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/budgets': {
      id: '/api/budgets'
      path: '/api/budgets'
      fullPath: '/api/budgets'
      preLoaderRoute: typeof ApiBudgetsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bill-reminders': {
      id: '/api/bill-reminders'
      path: '/api/bill-reminders'
      fullPath: '/api/bill-reminders'
      preLoaderRoute: typeof ApiBillRemindersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/summary': {
      id: '/api/transactions/summary'
      path: '/summary'
      fullPath: '/api/transactions/summary'
      preLoaderRoute: typeof ApiTransactionsSummaryRouteRouteImport
      parentRoute: typeof ApiTransactionsRouteRoute
    }
    '/api/transactions/$id': {
      id: '/api/transactions/$id'
      path: '/$id'
      fullPath: '/api/transactions/$id'
      preLoaderRoute: typeof ApiTransactionsIdRouteRouteImport
      parentRoute: typeof ApiTransactionsRouteRoute
    }
    '/api/recurring-transactions/$id': {
      id: '/api/recurring-transactions/$id'
      path: '/$id'
      fullPath: '/api/recurring-transactions/$id'
      preLoaderRoute: typeof ApiRecurringTransactionsIdRouteRouteImport
      parentRoute: typeof ApiRecurringTransactionsRouteRoute
    }
    '/api/investments/summary': {
      id: '/api/investments/summary'
      path: '/summary'
      fullPath: '/api/investments/summary'
      preLoaderRoute: typeof ApiInvestmentsSummaryRouteRouteImport
      parentRoute: typeof ApiInvestmentsRouteRoute
    }
    '/api/investments/history': {
      id: '/api/investments/history'
      path: '/history'
      fullPath: '/api/investments/history'
      preLoaderRoute: typeof ApiInvestmentsHistoryRouteRouteImport
      parentRoute: typeof ApiInvestmentsRouteRoute
    }
    '/api/investments/accounts': {
      id: '/api/investments/accounts'
      path: '/accounts'
      fullPath: '/api/investments/accounts'
      preLoaderRoute: typeof ApiInvestmentsAccountsRouteRouteImport
      parentRoute: typeof ApiInvestmentsRouteRoute
    }
    '/api/investments/$id': {
      id: '/api/investments/$id'
      path: '/$id'
      fullPath: '/api/investments/$id'
      preLoaderRoute: typeof ApiInvestmentsIdRouteRouteImport
      parentRoute: typeof ApiInvestmentsRouteRoute
    }
    '/api/financial-goals/$id': {
      id: '/api/financial-goals/$id'
      path: '/$id'
      fullPath: '/api/financial-goals/$id'
      preLoaderRoute: typeof ApiFinancialGoalsIdRouteRouteImport
      parentRoute: typeof ApiFinancialGoalsRouteRoute
    }
    '/api/debts-receivables/summary': {
      id: '/api/debts-receivables/summary'
      path: '/api/debts-receivables/summary'
      fullPath: '/api/debts-receivables/summary'
      preLoaderRoute: typeof ApiDebtsReceivablesSummaryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/budgets/$id': {
      id: '/api/budgets/$id'
      path: '/$id'
      fullPath: '/api/budgets/$id'
      preLoaderRoute: typeof ApiBudgetsIdRouteRouteImport
      parentRoute: typeof ApiBudgetsRouteRoute
    }
    '/api/bill-reminders/$id': {
      id: '/api/bill-reminders/$id'
      path: '/$id'
      fullPath: '/api/bill-reminders/$id'
      preLoaderRoute: typeof ApiBillRemindersIdRouteRouteImport
      parentRoute: typeof ApiBillRemindersRouteRoute
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receivables/$id/collect': {
      id: '/api/receivables/$id/collect'
      path: '/$id/collect'
      fullPath: '/api/receivables/$id/collect'
      preLoaderRoute: typeof ApiReceivablesIdCollectRouteRouteImport
      parentRoute: typeof ApiReceivablesRouteRoute
    }
    '/api/financial-goals/$id/contribute': {
      id: '/api/financial-goals/$id/contribute'
      path: '/contribute'
      fullPath: '/api/financial-goals/$id/contribute'
      preLoaderRoute: typeof ApiFinancialGoalsIdContributeRouteRouteImport
      parentRoute: typeof ApiFinancialGoalsIdRouteRoute
    }
    '/api/debts/$id/settle': {
      id: '/api/debts/$id/settle'
      path: '/$id/settle'
      fullPath: '/api/debts/$id/settle'
      preLoaderRoute: typeof ApiDebtsIdSettleRouteRouteImport
      parentRoute: typeof ApiDebtsRouteRoute
    }
    '/api/bill-reminders/$id/pay': {
      id: '/api/bill-reminders/$id/pay'
      path: '/pay'
      fullPath: '/api/bill-reminders/$id/pay'
      preLoaderRoute: typeof ApiBillRemindersIdPayRouteRouteImport
      parentRoute: typeof ApiBillRemindersIdRouteRoute
    }
  }
}

interface ApiBillRemindersIdRouteRouteChildren {
  ApiBillRemindersIdPayRouteRoute: typeof ApiBillRemindersIdPayRouteRoute
}

const ApiBillRemindersIdRouteRouteChildren: ApiBillRemindersIdRouteRouteChildren =
  {
    ApiBillRemindersIdPayRouteRoute: ApiBillRemindersIdPayRouteRoute,
  }

const ApiBillRemindersIdRouteRouteWithChildren =
  ApiBillRemindersIdRouteRoute._addFileChildren(
    ApiBillRemindersIdRouteRouteChildren,
  )

interface ApiBillRemindersRouteRouteChildren {
  ApiBillRemindersIdRouteRoute: typeof ApiBillRemindersIdRouteRouteWithChildren
}

const ApiBillRemindersRouteRouteChildren: ApiBillRemindersRouteRouteChildren = {
  ApiBillRemindersIdRouteRoute: ApiBillRemindersIdRouteRouteWithChildren,
}

const ApiBillRemindersRouteRouteWithChildren =
  ApiBillRemindersRouteRoute._addFileChildren(
    ApiBillRemindersRouteRouteChildren,
  )

interface ApiBudgetsRouteRouteChildren {
  ApiBudgetsIdRouteRoute: typeof ApiBudgetsIdRouteRoute
}

const ApiBudgetsRouteRouteChildren: ApiBudgetsRouteRouteChildren = {
  ApiBudgetsIdRouteRoute: ApiBudgetsIdRouteRoute,
}

const ApiBudgetsRouteRouteWithChildren = ApiBudgetsRouteRoute._addFileChildren(
  ApiBudgetsRouteRouteChildren,
)

interface ApiDebtsRouteRouteChildren {
  ApiDebtsIdSettleRouteRoute: typeof ApiDebtsIdSettleRouteRoute
}

const ApiDebtsRouteRouteChildren: ApiDebtsRouteRouteChildren = {
  ApiDebtsIdSettleRouteRoute: ApiDebtsIdSettleRouteRoute,
}

const ApiDebtsRouteRouteWithChildren = ApiDebtsRouteRoute._addFileChildren(
  ApiDebtsRouteRouteChildren,
)

interface ApiFinancialGoalsIdRouteRouteChildren {
  ApiFinancialGoalsIdContributeRouteRoute: typeof ApiFinancialGoalsIdContributeRouteRoute
}

const ApiFinancialGoalsIdRouteRouteChildren: ApiFinancialGoalsIdRouteRouteChildren =
  {
    ApiFinancialGoalsIdContributeRouteRoute:
      ApiFinancialGoalsIdContributeRouteRoute,
  }

const ApiFinancialGoalsIdRouteRouteWithChildren =
  ApiFinancialGoalsIdRouteRoute._addFileChildren(
    ApiFinancialGoalsIdRouteRouteChildren,
  )

interface ApiFinancialGoalsRouteRouteChildren {
  ApiFinancialGoalsIdRouteRoute: typeof ApiFinancialGoalsIdRouteRouteWithChildren
}

const ApiFinancialGoalsRouteRouteChildren: ApiFinancialGoalsRouteRouteChildren =
  {
    ApiFinancialGoalsIdRouteRoute: ApiFinancialGoalsIdRouteRouteWithChildren,
  }

const ApiFinancialGoalsRouteRouteWithChildren =
  ApiFinancialGoalsRouteRoute._addFileChildren(
    ApiFinancialGoalsRouteRouteChildren,
  )

interface ApiInvestmentsRouteRouteChildren {
  ApiInvestmentsIdRouteRoute: typeof ApiInvestmentsIdRouteRoute
  ApiInvestmentsAccountsRouteRoute: typeof ApiInvestmentsAccountsRouteRoute
  ApiInvestmentsHistoryRouteRoute: typeof ApiInvestmentsHistoryRouteRoute
  ApiInvestmentsSummaryRouteRoute: typeof ApiInvestmentsSummaryRouteRoute
}

const ApiInvestmentsRouteRouteChildren: ApiInvestmentsRouteRouteChildren = {
  ApiInvestmentsIdRouteRoute: ApiInvestmentsIdRouteRoute,
  ApiInvestmentsAccountsRouteRoute: ApiInvestmentsAccountsRouteRoute,
  ApiInvestmentsHistoryRouteRoute: ApiInvestmentsHistoryRouteRoute,
  ApiInvestmentsSummaryRouteRoute: ApiInvestmentsSummaryRouteRoute,
}

const ApiInvestmentsRouteRouteWithChildren =
  ApiInvestmentsRouteRoute._addFileChildren(ApiInvestmentsRouteRouteChildren)

interface ApiReceivablesRouteRouteChildren {
  ApiReceivablesIdCollectRouteRoute: typeof ApiReceivablesIdCollectRouteRoute
}

const ApiReceivablesRouteRouteChildren: ApiReceivablesRouteRouteChildren = {
  ApiReceivablesIdCollectRouteRoute: ApiReceivablesIdCollectRouteRoute,
}

const ApiReceivablesRouteRouteWithChildren =
  ApiReceivablesRouteRoute._addFileChildren(ApiReceivablesRouteRouteChildren)

interface ApiRecurringTransactionsRouteRouteChildren {
  ApiRecurringTransactionsIdRouteRoute: typeof ApiRecurringTransactionsIdRouteRoute
}

const ApiRecurringTransactionsRouteRouteChildren: ApiRecurringTransactionsRouteRouteChildren =
  {
    ApiRecurringTransactionsIdRouteRoute: ApiRecurringTransactionsIdRouteRoute,
  }

const ApiRecurringTransactionsRouteRouteWithChildren =
  ApiRecurringTransactionsRouteRoute._addFileChildren(
    ApiRecurringTransactionsRouteRouteChildren,
  )

interface ApiTransactionsRouteRouteChildren {
  ApiTransactionsIdRouteRoute: typeof ApiTransactionsIdRouteRoute
  ApiTransactionsSummaryRouteRoute: typeof ApiTransactionsSummaryRouteRoute
}

const ApiTransactionsRouteRouteChildren: ApiTransactionsRouteRouteChildren = {
  ApiTransactionsIdRouteRoute: ApiTransactionsIdRouteRoute,
  ApiTransactionsSummaryRouteRoute: ApiTransactionsSummaryRouteRoute,
}

const ApiTransactionsRouteRouteWithChildren =
  ApiTransactionsRouteRoute._addFileChildren(ApiTransactionsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DebtsReceivablesRoute: DebtsReceivablesRoute,
  ExpensesRoute: ExpensesRoute,
  IncomeRoute: IncomeRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiBillRemindersRouteRoute: ApiBillRemindersRouteRouteWithChildren,
  ApiBudgetsRouteRoute: ApiBudgetsRouteRouteWithChildren,
  ApiDashboardRouteRoute: ApiDashboardRouteRoute,
  ApiDebtsRouteRoute: ApiDebtsRouteRouteWithChildren,
  ApiFinancialGoalsRouteRoute: ApiFinancialGoalsRouteRouteWithChildren,
  ApiInvestmentsRouteRoute: ApiInvestmentsRouteRouteWithChildren,
  ApiReceivablesRouteRoute: ApiReceivablesRouteRouteWithChildren,
  ApiRecurringTransactionsRouteRoute:
    ApiRecurringTransactionsRouteRouteWithChildren,
  ApiTransactionsRouteRoute: ApiTransactionsRouteRouteWithChildren,
  ApiAuthLoginRouteRoute: ApiAuthLoginRouteRoute,
  ApiAuthLogoutRouteRoute: ApiAuthLogoutRouteRoute,
  ApiAuthMeRouteRoute: ApiAuthMeRouteRoute,
  ApiAuthRegisterRouteRoute: ApiAuthRegisterRouteRoute,
  ApiDebtsReceivablesSummaryRouteRoute: ApiDebtsReceivablesSummaryRouteRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
